### ISSUE TITLE
livereload no server listening

### ISSUE THREAD

**Issue by Euheny** [vanjacosic/run-wintersmith#4]
Greetings. Tell me what I'm doing wrong.
I took the example-gulpfile.js but when you try to save the templates get:
gulp: livereload no server listening, nothing notified.

**Comment by vanjacosic** [comment]
Sorry for the late reply, I have been away for a few weeks.

I'm not sure why this issue happens, could you tell me about your setup?

**Comment by Euheny** [comment]
The question is no longer relevant. I refused to winterыьшер in favor of my own assembly gulp
